import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/Header'
import { useValidation } from "../hooks/validation/useValidation.tsx"
import { useAuth } from "../hooks/useAuth.tsx"

const factoryAddress = "0x6343A758F34E097a3122e0B9eCDe480BAe2E5C4B"
const curationPassAddress = "0xc3ed34368d7d8570c6fdd4b7f65dbcbf26f813ce"
const curationManagerAddress = ""

const Validation: NextPage = () => {

  const { address } = useAuth()

  const currentAddress = address
    ? address
    : "no user logged in"

  const { isValidated, error, isLoading } = useValidation(
    curationPassAddress,
    address
  )

  return (
    <div className='flex flex-col justify-center h-screen min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex flex-col items-center">        
        <h1 className="text-white">
          {currentAddress}
        </h1>
        <h1 className="text-white">
          {"curation pass adderss = " + curationPassAddress}
        </h1>        
        <h1 className="text-white">
          { isValidated
            ? "user owns curation pass ✅"
            : "user DOES NOT own curation pass ❌"
          }
        </h1>                
      </main>
    </div>
  )
}

export default Validation